#!/usr/bin/env sh

npm run format

# Chạy ESLint kiểm tra và dừng commit nếu có lỗi
echo "Running ESLint check..."
npm run lint
if [ $? -ne 0 ]; then
  echo "❌ ESLint check failed. Fix the errors before committing."
  exit 1
fi

echo "✅ ESLint check passed"